name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build (Node 12)
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build
    - name: Deploy (S3)
      uses: Reggionick/s3-deploy@v3.1.0
      with:
        folder: public
        bucket: locksha.re
        bucket-region: eu-west-1
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        delete-removed: true
    - name: Deploy (S3)
      uses: shallwefootball/upload-s3-action@v1.1.3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: locksha.re
        source_dir: public
