name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build (Node 12)
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build
    - name: Deploy
      uses: kazimanzurrashid/aws-static-web-app-update-action@v1
      with:
        location: './public'
        bucket: 'locksha.re'
        invalidate: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
